apiVersion: v1
kind: Namespace
metadata:
  name: email-services
  labels:
    name: email-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-processor-service
  namespace: email-services
  labels:
    app: email-processor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-processor-service
  template:
    metadata:
      labels:
        app: email-processor-service
    spec:
      serviceAccountName: email-processor-service
      containers:
      - name: email-processor-service
        image: ${EMAIL_PROCESSOR_IMAGE}
        env:
        - name: SQS_QUEUE_URL_PARAMETER
          value: "/email-service/sqs-queue-url"
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: email-processor-config
              key: s3_bucket_name
        - name: AWS_REGION
          value: "us-west-2"
        - name: POLL_INTERVAL_SECONDS
          value: "30"
        - name: MAX_MESSAGES_PER_POLL
          value: "10"
        - name: VISIBILITY_TIMEOUT_SECONDS
          value: "300"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: email-processor-config
  namespace: email-services
data:
  s3_bucket_name: "${S3_BUCKET_NAME}"
  aws_region: "us-west-2"
  poll_interval_seconds: "30"
  max_messages_per_poll: "10"
  visibility_timeout_seconds: "300"
---
apiVersion: v1
kind: Service
metadata:
  name: email-processor-service
  namespace: email-services
  labels:
    app: email-processor-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: email-processor-service
